// Reglas de prioridad y casos de estudio — ЗДвП
// Cada entrada: t=titulo, art=articulo, txt=cuerpo, cl=clave para recordar
var LEYES=[
{id:"jer",t:"Quien manda sobre quien",art:"Jerarquia",
txt:"Antes de aplicar ninguna regla de prioridad, mira quien esta regulando. El orden es fijo y nunca se invierte: primero el REGULADOR o agente, que anula todo lo demas. Despues el SEMAFORO, que anula las senales de prioridad. Despues las SENALES VERTICALES, que anulan las marcas viales. Despues las MARCAS VIALES. Y por ultimo las reglas generales, que solo se aplican si no hay nada de lo anterior.",
cl:"El semaforo anula las senales de PRIORIDAD, pero no las de prohibicion ni las de obligacion. Un verde no te autoriza a girar donde una senal lo impide."},

{id:"a47",t:"Velocidad al acercarse al cruce",art:"чл. 47",
txt:"Al acercarte a un cruce debes circular a una velocidad que te permita parar y ceder el paso a quien tenga preferencia.",
cl:"No es una regla de prioridad: es la que hace posibles a las demas. Si llegas demasiado rapido ya has infringido, aunque despues cedas."},

{id:"a48",t:"Regla de la derecha",art:"чл. 48",
txt:"En un cruce de vias de igual valor, cede el paso a los vehiculos que se encuentran o se aproximan por tu derecha. Y todo vehiculo sin railes cede el paso a los vehiculos sobre railes, es decir a los tranvias, sea cual sea su posicion y su direccion de marcha.",
cl:"Dice se encuentran O se aproximan: tambien cuenta el que ya esta detenido en el cruce. Y el tranvia tiene preferencia siempre, incluso viniendo por tu izquierda. Es la unica excepcion real a la regla de la derecha."},

{id:"a49",t:"Salir de un camino de tierra",art:"чл. 49",
txt:"Quien sale de un camino de tierra a una via pavimentada cede el paso a los vehiculos y tambien a los peatones que circulan por la via pavimentada.",
cl:"Fijate en que menciona a los peatones expresamente, no solo a los vehiculos."},

{id:"a50a",t:"Via con prioridad",art:"чл. 50 apartado 1",
txt:"En un cruce donde una de las vias esta senalizada como via con prioridad, los conductores que vienen de las demas vias ceden el paso a los que circulan por ella.",
cl:"El rombo amarillo, el STOP y el ceda el paso son las senales que reparten esto."},

{id:"a50b",t:"Cuando la prioritaria cambia de direccion",art:"чл. 50 apartado 2",
txt:"Cuando en un cruce se indica que la via con prioridad cambia de direccion, los conductores que se encuentran en esa via se rigen entre si por las reglas del articulo 48, o sea por la regla de la derecha. Y por esas mismas reglas se rigen entre si los conductores que NO se encuentran en la via con prioridad.",
cl:"Cubre las dos capas a la vez. Prioritaria contra secundaria manda la prioritaria. Prioritaria contra prioritaria, regla de la derecha. Secundaria contra secundaria, regla de la derecha tambien. El panel bajo el rombo dibuja la prioritaria con trazo GRUESO y la secundaria con trazo FINO."},

{id:"a37",t:"Giro a la izquierda",art:"чл. 37 apartado 1",
txt:"Al girar a la izquierda para entrar en otra via, cedes el paso a los vehiculos que circulan en sentido contrario. En concreto a los que siguen de frente y a los que giran a la derecha.",
cl:"Es la regla que mas accidentes reparte. Si chocas girando a la izquierda contra uno que venia de frente, respondes tu. Y no te libra ir por la via con prioridad."},

{id:"a38",t:"Cambio de sentido o media vuelta",art:"чл. 38",
txt:"El cambio de sentido se hace hacia la izquierda desde el carril situado mas a la izquierda. Al hacerlo, cedes el paso a los vehiculos que circulan en sentido contrario.",
cl:"Girar a la izquierda y cambiar de sentido no son lo mismo. Una flecha verde a la izquierda te permite girar, pero no dar media vuelta."},

{id:"a39",t:"Donde esta prohibido cambiar de sentido",art:"чл. 39",
txt:"Esta prohibido cambiar de sentido en un paso de peatones, en un paso a nivel, en un puente, en un viaducto, en un tunel, en un paso subterraneo, con visibilidad limitada, o con visibilidad reducida por debajo de cincuenta metros.",
cl:"Memoriza los cincuenta metros: es el numero que suele preguntarse."},

{id:"a119",t:"Paso de peatones",art:"чл. 119 apartado 1",
txt:"Al aproximarte a un paso de peatones, el conductor de un vehiculo sin railes cede el paso a los peatones que lo estan utilizando.",
cl:"Si el paso esta regulado por semaforo o por agente, manda esa senal. Un peaton que cruza con su semaforo en rojo pierde la preferencia, pero eso no te libra de circular a velocidad segura."},

{id:"a117",t:"Ninos en la via",art:"чл. 117",
txt:"Al acercarte a un lugar donde hay ninos en la via o cerca de ella, debes reducir la velocidad y, si hace falta, detenerte.",
cl:"Es una obligacion activa, no solo de precaucion."},

{id:"a15",t:"Carril: donde debes circular",art:"Regla general",
txt:"Fuera de poblacion se circula lo mas a la derecha posible: por el carril derecho si hay marcas, y pegado al borde derecho si no las hay. En autopista, por el derecho, usando los de la izquierda solo para adelantar y volviendo al derecho al terminar. Dentro de poblacion puedes elegir el carril que te resulte mas comodo, pero solo si se cumplen tres condiciones a la vez: dos o mas carriles en el mismo sentido, el numero de carriles y sus direcciones senalizados, y velocidad permitida no superior a 80 kilometros por hora.",
cl:"Memoriza el 80. Y recuerda que el carril izquierdo se ocupa para adelantar y se abandona al terminar: nunca es un carril de viaje."},

{id:"amag",t:"Autopista: incorporacion y vehiculos lentos",art:"Autopista",
txt:"Quien entra en la autopista desde el carril de aceleracion cede el paso a quien ya circula por ella. La regla de la derecha no se aplica en una incorporacion: vale entre vias que se cruzan. El vehiculo lento, definido como el que no puede superar los treinta kilometros por hora, tiene su propio carril senalizado cuando existe, y en el pueden circular tanto los que llevan el distintivo de vehiculo lento como los que no alcanzan esa velocidad, sean tractores o camiones.",
txt2:"NUMEROS DE AUTOPISTA. Solo pueden circular vehiculos cuya velocidad maxima por construccion supere los CINCUENTA kilometros por hora: por eso el tractor tiene prohibida la entrada. Se circula siempre por el carril libre mas a la derecha. Cuando hay TRES o mas carriles en el mismo sentido, los vehiculos de mas de TRES COMA CINCO toneladas y los conjuntos de mas de SIETE metros de longitud total solo pueden usar el carril derecho y el contiguo. El carril de emergencia sirve unicamente para detenerse por averia.",
cl:"El criterio para el carril de lentos es la velocidad que alcanza el vehiculo, no su tipo. Y la velocidad nunca da preferencia a nadie, ni en autopista ni en ningun sitio. Numeros que caen: 50 para entrar en autopista, 30 para ser vehiculo lento, 3,5 toneladas y 7 metros para el carril izquierdo, 80 para elegir carril en poblacion."},

{id:"orden",t:"Orden de decision paso a paso",art:"Metodo",
txt:"Uno. Hay un agente. Si lo hay, obedece solo sus senales y termina ahi. Dos. Hay semaforo en funcionamiento. Si lo hay, obedecelo, pero recuerda que las senales de prohibicion y de obligacion siguen vigentes. Tres. Hay senales de prioridad, STOP, ceda el paso o rombo. Aplica el articulo 50, y si el panel muestra que la prioritaria gira, aplica el apartado 2. Cuatro. No hay nada. Entonces son vias de igual valor y manda la regla de la derecha. Cinco. En cualquiera de los casos anteriores, ademas: si giras a la izquierda o das media vuelta cedes al de frente, si hay un tranvia tiene preferencia siempre, y si hay un paso de peatones cedes a los peatones.",
cl:"Aplicado en este orden, casi cualquier pregunta de prioridad se resuelve sin dudar."},

{id:"cebos",t:"Los cebos que se repiten",art:"Trampas",
txt:"Tengo prioridad porque voy recto: falso, la direccion nunca reparte preferencias. Tengo prioridad porque senalice primero: falso, el intermitente avisa pero no otorga derechos. Tengo prioridad porque llegue antes: falso, llegar antes no es tener preferencia. La moto tiene prioridad por ser de dos ruedas: falso, se rige por las mismas reglas. Voy por la prioritaria asi que no cedo a nadie: falso, si giras a la izquierda cedes al de frente igual. El verde me deja girar donde quiera: falso, no anula prohibiciones ni obligaciones. Con un STOP cedo a todo lo que se mueve: falso, solo a quien circula por la via con prioridad.",
cl:"Cuando una opcion empiece por porque voy recto, desconfia."}
];

// Casos singulares que han aparecido al estudiar preguntas concretas
var CASOS=[
{id:"k6546",im:[{q:"6546",f:"68490",a:"Giras a la izquierda, el rojo viene de frente siguiendo recto y el azul cruza desde tu izquierda. Los tres se ceden en circulo. En el examen marca pasar antes que los dos. En carretera, detente y cede al que viene de frente."}],im:[{f:"68490",q:"6546",a:"Giras a la izquierda. El rojo viene de frente recto y el azul cruza desde tu izquierda. EN EL EXAMEN: paso antes que los dos. EN CARRETERA: cede al de frente."}],t:"Bucle de prioridad",p:"6546, 6543, 6550",
txt:"Giras a la izquierda, un coche viene de frente siguiendo recto, y un tercero cruza desde tu izquierda. Aplicando la ley sale un circulo: tu cedes al de frente por el articulo 37, el de frente cede al que cruza porque le entra por su derecha, y el que cruza te cede a ti porque te llega por tu izquierda. Nadie puede arrancar primero. En bulgaro lo llaman zakleshtvane, atasco de prioridad.",
cl:"La ley no resuelve estos bucles con ninguna regla: se salen por acuerdo entre conductores. En esta pregunta la respuesta oficial del banco contradice al articulo 37. En el examen marca lo que dice el banco. En carretera, cede al que viene de frente."},

{id:"k6408",im:[{q:"6408",f:"71573",a:"El circulo rojo con dos automoviles prohibe adelantar, pero la moto de dos ruedas queda fuera de la prohibicion. Comprueba que no lleva sidecar y adelanta con normalidad."}],im:[{f:"71573",q:"6408",a:"Senal de prohibido adelantar y un motorista delante. QUE HACER: puedes adelantarle, la senal no cubre a las motos de dos ruedas sin sidecar."}],t:"Prohibido adelantar no incluye motos",p:"6408",
txt:"La senal circular roja con dos automoviles prohibe adelantar, pero deja fuera expresamente a los ciclomotores y a las motocicletas de dos ruedas sin sidecar.",
cl:"Se ve el circulo rojo y se asume prohibicion total. Lo que prohibe es adelantar automoviles, no motos."},

{id:"k5900",im:[{q:"5900",f:"41967",a:"Roja y ambar encendidas a la vez. Mete la marcha y preparate para salir, pero no muevas el coche hasta que aparezca el verde."}],im:[{f:"41967",q:"5900",a:"Roja y ambar encendidas juntas. QUE HACER: permanecer detenido. Prepara la salida pero no arranques hasta el verde."}],t:"Roja y ambar encendidas a la vez",p:"5900",
txt:"Cuando se encienden la roja y la ambar juntas, no se autoriza a pasar. Avisa de que el verde esta a punto de llegar para que prepares la salida, pero hasta que aparezca sigues detenido.",
cl:"Si la roja esta encendida da igual lo que la acompane. El paso esta prohibido."},

{id:"ksem",im:[{q:"6608",f:"51516",a:"Verde encendido, un ceda el paso encima y una senal azul de direccion obligatoria recto. El verde anula el ceda el paso, pero la azul sigue mandando: solo puedes seguir de frente."},{q:"5952",f:"51499",a:"Verde encendido bajo un STOP y una senal de prohibido girar a la derecha. El verde anula el STOP; la prohibicion de giro sigue vigente."}],im:[{f:"51516",q:"6608",a:"Verde encendido, triangulo de ceda el paso y disco azul de direccion obligatoria recto. QUE HACER: obedecer el semaforo Y la direccion obligatoria. La de prioridad no cuenta."},{f:"51499",q:"5952",a:"Verde encendido, STOP arriba y senal de prohibido girar a la derecha. QUE HACER: pasar con el verde pero sin girar a la derecha. El STOP queda anulado."}],t:"Que anula y que no anula el semaforo",p:"6608, 5952",
txt:"Un semaforo en funcionamiento deja sin efecto las senales de prioridad, incluido el STOP. Pero no toca las senales de prohibicion ni las de obligacion: una senal azul de direccion obligatoria o una de prohibido girar siguen vigentes con el verde encendido.",
cl:"El verde autoriza a pasar, no a tomar una direccion que otra senal impone o prohibe."},

{id:"kreg",im:[{q:"5871",f:"37240",a:"Brazo derecho extendido al frente y lo ves por su costado izquierdo: se abren todas las direcciones, incluida la media vuelta."},{q:"5837",f:"24081",a:"Brazos bajados y lo ves de perfil: puedes seguir recto o girar a la derecha. Quien ve su pecho o su espalda se detiene."},{q:"6668",f:"54674",a:"Brazo levantado en vertical: alto para todos. Solo continua quien ya tenia el paso autorizado o quien esta tan cerca que no puede detenerse con seguridad."}],im:[{f:"37240",q:"5871",a:"Brazo derecho extendido al frente y lo ves por su costado izquierdo. QUE HACER: puedes ir en todas las direcciones, incluida la media vuelta."},{f:"24081",q:"5837",a:"Brazos bajados y lo ves de perfil. QUE HACER: los de los costados siguen recto o giran a la derecha. Los del pecho y la espalda se detienen."},{f:"54674",q:"6668",a:"Brazo levantado en vertical. QUE HACER: detenerse. Solo siguen quien ya tenia el paso autorizado o quien no puede parar con seguridad."}],t:"Senales del regulador",p:"5871, 5837, 6668",
txt:"Brazos bajados: pasan los que lo ven de costado, por su izquierda o por su derecha, y pueden seguir recto o girar a la derecha. Los que ven su pecho o su espalda se detienen. Brazo derecho extendido al frente: desde su costado izquierdo se abre todo, recto, izquierda, derecha y media vuelta. Desde el pecho solo se permite girar a la derecha. Desde su derecha y desde su espalda esta prohibido. Brazo levantado en vertical: atencion, alto para todos, salvo quien ya tenia el paso autorizado o esta tan cerca que no puede detenerse con seguridad.",
cl:"Cuando hay agente, el semaforo deja de decidir."},

{id:"ksemvsder",im:[{q:"5929",f:"48329",a:"Solo hay senales. Los de la via con prioridad pasan primero, y entre ellos se ordenan por la regla de la derecha. La regla del giro a la izquierda existe, pero aqui nadie gira a la izquierda, asi que no interviene."},{q:"5935",f:"103109",a:"Aqui hay semaforo. Pasan los que tienen verde, y los que giran a la izquierda ceden a los de frente. La regla de la derecha NO se aplica: el semaforo ya reparte el paso por fases."}],
t:"Con semaforo la regla de la derecha NO se aplica",p:"5929, 5935",
txt:"Cuando el cruce lo regula un semaforo, el orden de paso lo marcan las fases del semaforo y no la posicion relativa de los vehiculos. Entre dos conductores que tienen verde a la vez no se aplica la regla de la derecha. Lo que si sigue vigente es que el que gira a la izquierda cede el paso al que viene de frente, porque eso no depende del semaforo sino de la maniobra.",
cl:"Solo senales: manda la posicion, o sea la regla de la derecha. Con semaforo: mandan las fases. La unica regla que sobrevive en los dos casos es la del giro a la izquierda."},

{id:"kprohib",im:[{q:"5896",f:"48224",a:"Hay un agente regulando y ademas una senal de prohibido girar a la derecha. El agente decide quien pasa, pero no te autoriza a tomar una direccion prohibida por una senal. La respuesta es no."},{q:"6608",f:"51516",a:"Semaforo en verde, un ceda el paso y una senal azul de direccion obligatoria recto. El verde anula el ceda el paso, pero la azul sigue mandando."}],
t:"Que anulan el agente y el semaforo, y que no",p:"5896, 6608",
txt:"Tanto el agente como el semaforo dejan sin efecto las senales que reparten la PRIORIDAD: el STOP, el ceda el paso y el rombo de via con prioridad. Pero ninguno de los dos anula las senales de PROHIBICION ni las de OBLIGACION. Una senal de prohibido girar o una azul de direccion obligatoria siguen vigentes aunque haya un agente dirigiendo o el semaforo este en verde.",
cl:"Quien regula el paso decide QUIEN pasa, no HACIA DONDE puedes ir. Esa distincion se repite en todo el examen."},

{id:"kmag3",im:[{q:"5380",f:"41655",a:"Tres carriles mas el de emergencia. El tractor circula por el carril de emergencia y ademas no puede entrar en autopista. El turismo va por el central teniendo libre el derecho. El camion ocupa el carril izquierdo, vedado a los de mas de 3,5 toneladas cuando hay tres o mas carriles. Los tres infringen."},{q:"5375",f:"41441",a:"Circular por el carril izquierdo con el derecho libre. En autopista los carriles de la izquierda son solo para adelantar y se abandonan al terminar."}],
t:"Autopista: tres infracciones distintas",p:"5380, 5375",
txt:"En autopista concurren varias reglas a la vez y conviene revisarlas una por una. Primera: solo entran los vehiculos que superan los cincuenta kilometros por hora por construccion, asi que tractores y maquinaria lenta quedan fuera. Segunda: se circula por el carril libre mas a la derecha, y los de la izquierda son solo para adelantar. Tercera: con tres o mas carriles, los vehiculos de mas de tres coma cinco toneladas y los conjuntos de mas de siete metros solo pueden usar el derecho y el contiguo. Cuarta: el carril de emergencia sirve solo para detenerse por averia, nunca para circular.",
cl:"Cuando una pregunta de autopista ofrezca solo el tractor, solo el camion o solo el turismo, sospecha: suele fallar mas de uno. Revisa los cuatro puntos antes de elegir."},

{id:"kcarril",im:[{q:"6076",f:"60500",a:"Fuera de poblacion, el rojo circula por el carril izquierdo teniendo libre el derecho. Es infraccion aunque en ese momento no moleste a nadie."},{q:"6099",f:"63839",a:"En poblacion, con dos o mas carriles en el mismo sentido, eliges el carril que te resulte mas comodo. La misma maniobra de arriba, aqui es correcta."}],im:[{f:"60500",q:"6076",a:"Fuera de poblacion, circulando por el carril izquierdo con el derecho libre. QUE HACER: bajarse al carril derecho. Asi es infraccion."},{f:"63839",q:"6099",a:"En poblacion, con varios carriles en el mismo sentido. QUE HACER: puedes seguir en el carril que te resulte mas comodo. Aqui no hay obligacion de ir a la derecha."}],t:"Carril: dentro y fuera de poblacion",p:"6076, 6077, 6099",
txt:"Fuera de poblacion hay que circular lo mas a la derecha posible: por el carril derecho si hay marcas que delimiten carriles, y lo mas a la derecha de la calzada si no las hay. Dentro de poblacion, con dos o mas carriles en el mismo sentido, el conductor elige el carril que le resulte mas comodo.",
cl:"La misma maniobra es correcta en ciudad e infraccion en carretera. Mira siempre si estas dentro o fuera de poblacion antes de responder."},

{id:"k6090",im:[{q:"6090",f:"62058",a:"Calzada de cuatro carriles. Prohibido invadir los del sentido contrario en cualquier circunstancia, tampoco para adelantar."}],im:[{f:"62058",q:"6090",a:"Calzada de cuatro carriles o mas. QUE HACER: no invadir nunca los del sentido contrario, ni siquiera para adelantar."}],t:"Calzada de cuatro carriles o mas",p:"6090",
txt:"Cuando la calzada tiene cuatro carriles o mas, esta prohibido invadir los carriles del sentido contrario en cualquier circunstancia.",
cl:"No hay excepcion por adelantar, que es el cebo habitual. Con cuatro carriles se adelanta por el carril del propio sentido. Cuenta los carriles antes de pensar en cruzarte."},

{id:"kbus",im:[{q:"9840",f:"270043260",a:"Linea amarilla continua y BUS pintado en el asfalto. Reservado a lineas regulares de transporte publico; la continua no se pisa."},{q:"6446",f:"64672",a:"La senal indica que el carril derecho es BUS. Mismo criterio: solo el servicio de linea regular puede circular por el."}],im:[{f:"270043260",q:"9840",a:"Carril BUS con linea amarilla continua. QUE HACER: no entrar. Reservado a lineas regulares de transporte publico."},{f:"64672",q:"6446",a:"Senal que designa el carril BUS. QUE HACER: mismo criterio, solo lineas regulares."}],t:"Carril BUS",p:"9840, 6446",
txt:"El carril BUS esta reservado a los vehiculos de lineas regulares de transporte publico de pasajeros. La linea amarilla continua que lo delimita no se puede pisar.",
cl:"Manda el servicio de linea regular, no el tipo ni el tamano del vehiculo. Un autocar privado no entra, y los taxis tampoco salvo que una senal lo autorice."},

{id:"klento",im:[{q:"6492",f:"65857",a:"Tres carriles. El vehiculo lento va por el derecho. Puede usar el central para rodear un obstaculo y el izquierdo para girar, nunca para adelantar."}],im:[{f:"65857",q:"6492",a:"Tres carriles y un vehiculo lento delante. QUE HACER (si eres el lento): ir por el carril derecho; el central solo para rodear un obstaculo y el izquierdo solo para girar."}],t:"Vehiculo lento",p:"6492",
txt:"El vehiculo lento debe circular por el carril situado mas a la derecha. Puede salir de el en dos casos concretos: usar el carril central para rodear un obstaculo, y el carril izquierdo para girar.",
cl:"Lo que no puede es usar el carril izquierdo para adelantar. Sale de su carril para esquivar o para girar, nunca para adelantar."},
{id:"ksemcolor",im:[{f:"43199",q:"5912",a:"Cuatro semaforos y hay que elegir el del ambar solo. AMBAR FIJO significa Atencion, para. Solo sigue el que ya ha entrado en el cruce o no podria detenerse sin frenar bruscamente."},{f:"42122",q:"5902",a:"Rojo solo y rojo+ambar son los dos que significan prohibido el paso. El rojo+ambar solo anuncia que llega el verde: mientras el rojo este encendido, sigue prohibido."}],t:"Que significa cada foco del semaforo",art:"чл. 31 ППЗДвП",p:"5902, 5908, 5912",
txt:"Cada combinacion tiene un nombre oficial y el examen pregunta por ese nombre. VERDE: el paso esta permitido, y es la unica que autoriza a pasar. AMBAR FIJO: Atencion, para. Prohibe entrar en el cruce; solo continua quien ya entro o no puede detenerse sin frenado brusco. ROJO: el paso esta prohibido. ROJO MAS AMBAR: el paso sigue prohibido, solo anuncia que el verde esta a punto de llegar.",
cl:"Dos cebos. El rojo+ambar se lee como arranca ya, y no: mientras haya rojo, prohibido. Y si preguntan cuales significan prohibido el paso, son rojo y rojo+ambar; el ambar solo tiene nombre propio, Atencion para. Ojo tambien a la palabra nemigasti, no parpadeantes: el ambar intermitente significa otra cosa, cruce sin regular."},

{id:"ktricruce",im:[{f:"55267",q:"6675",a:"Triangulo con un aspa negra: cruce de vias de igual valor. Despues de esta senal cedes a los que llegan por tu DERECHA."},{f:"55266",q:"6675",a:"Triangulo con trazo vertical grueso y un ramal fino a la derecha: cruce con via secundaria por la derecha. Aqui el grueso eres tu, no cedes."}],t:"Triangulos de cruce: el grosor manda",p:"6675",
txt:"En los triangulos rojos que avisan de un cruce, el GROSOR del trazo dice quien tiene prioridad. Trazo grueso es la via con prioridad, trazo fino la secundaria. Si el dibujo lleva un trazo grueso, tu vas por el y no cedes a los ramales finos. El aspa negra es distinta: no tiene trazo grueso porque no hay jerarquia, es cruce de vias de igual valor y devuelve el cruce a la regla de la derecha del чл. 50 apartado 1.",
cl:"El aspa es la unica de la familia que te obliga a ceder por la derecha. La glorieta no vale como respuesta a esa pregunta: alli cede el que entra, y los del anillo te llegan por la IZQUIERDA."},

{id:"kportico",im:[{f:"64344",q:"6435",a:"Portico con dos paneles: aspa sobre mi carril y flecha hacia abajo sobre el derecho. QUE HACER: pasar al carril derecho."}],t:"Semaforos de carril (portico)",art:"чл. 33 ППЗДвП",p:"6435",
txt:"Los paneles que cuelgan de un portico son semaforos de carril (чл. 33 ППЗДвП): no regulan el cruce, regulan si ese carril concreto se puede usar ahora. La ley describe la luz roja como DOS BANDAS INCLINADAS QUE SE CRUZAN, un aspa, y significa que la circulacion por el carril esta prohibida. La luz verde tiene forma de FLECHA HACIA ABAJO y significa que la circulacion por el carril esta permitida. Se leen mirando el panel que esta justo encima de TU carril, no el mas visible.",
cl:"Aspa encima = fuera de ese carril, aunque este vacio y no haya obras a la vista. Flecha abajo = por ese si. Y si ninguna de las dos luces esta encendida, el sentido del carril lo marca la senal Д1 (чл. 33, ал. 5)."},

{id:"kflechascarril",im:[{f:"64417",q:"6438",a:"Senal blanca rectangular con tres flechas verticales: la de la izquierda hacia abajo, las otras dos hacia arriba. El carril izquierdo es del sentido contrario; los otros dos son nuestros."}],t:"Senal Д1: numero y sentido de los carriles",art:"Д1",p:"6438",
txt:"Se llama Д1, Broy na patnite lenti i posoki za dvizhenie po tyah: numero de carriles y sentidos de circulacion por ellos. Es del grupo D, senales con prescripciones especiales. Rectangulo blanco con una flecha vertical por carril; el numero de flechas coincide con el numero de carriles y la norma permite indicar tambien los carriles del sentido contrario. Flecha hacia arriba: carril de tu sentido. Flecha hacia abajo: carril del sentido contrario. Se coloca en vias con dos o mas carriles en un sentido y vale hasta la siguiente interseccion.",
cl:"Tres carriles no significa tres carriles tuyos. Antes de cambiar de carril en una calzada ancha sin separacion fisica, cuenta las flechas y mira cual apunta hacia abajo."},
{id:"kregulador",im:[{f:"24291",q:"5839",a:"CASO 1. Brazos bajados, agente DE CARA a la camara. Eje de hombros = linea amarillo-azul: esos dos pasan (recto o derecha). Rojo ve el pecho y verde la espalda: parados."},{f:"36529",q:"5859",a:"CASO 3. Brazo derecho extendido, agente de perfil mirando al amarillo. Solo pasa quien ve su HOMBRO IZQUIERDO: el rojo. El verde ve el hombro derecho y con este gesto tambien esta parado."},{f:"39253",q:"5888",a:"CASO 4. Dyasna raka, vdignata vertikalno. Vnimanie, spri. Alto para todos; los que ya estan dentro del cruce deben despejarlo."}],t:"El agente regulador: los 3 gestos y el metodo",art:"ЗДвП чл. 10, ал. 2",p:"5834, 5837, 5839, 5841, 5845, 5847, 5850, 5853, 5857, 5859, 5867, 5869, 5871, 5873, 5876, 5882, 5885, 5888",
txt:"LO QUE DICE LA LEY, чл. 10, ал. 2 ЗДвП, literal. GESTO 1 — дясна ръка, вдигната вертикално, brazo derecho levantado en vertical: significa «Внимание, спри!», Atencion, para. No se aplica a los conductores que, tras haberseles permitido el paso, estan tan cerca del agente que no pueden detenerse sin crear peligro; y los que ya han entrado en el cruce deben despejarlo. GESTO 2 — ръка или ръце, протегнати хоризонтално встрани, brazo o brazos extendidos horizontalmente a los lados (tras el gesto el agente puede bajar los brazos, y sigue valiendo): a) «Преминаването е разрешено», paso permitido, para los conductores que se encuentran frente al hombro izquierdo o derecho del agente Y QUE VAN A SEGUIR RECTO O A GIRAR A LA DERECHA, y para los peatones que quieran cruzar por delante del pecho o por detras de la espalda; b) «Преминаването е забранено», paso prohibido, para todos los demas participantes. GESTO 3 — дясна ръка, протегната хоризонтално напред, brazo derecho extendido horizontalmente hacia delante: a) «Преминаването е разрешено» para los conductores que se encuentran frente al HOMBRO IZQUIERDO del agente, y para los peatones que quieran cruzar por detras de su espalda; b) «Преминаването е забранено» para todos los demas. Ademas, ал. 3 permite al agente usar gestos adicionales comprensibles para dar otras indicaciones. Y una regla que decide muchas preguntas: cuando los signos del agente contradicen al semaforo o a las senales de prioridad, MANDA EL AGENTE.",
cl:"EL METODO GEOMETRICO, en cuatro pasos y por este orden. PASO 1: mira el brazo. Si esta VERTICAL hacia arriba, se acabo el analisis: alto para todos. PASO 2: si no, pregunta que parte del agente te muestra a TI. Traza mentalmente la linea de sus hombros, el EJE. Solo hay tres respuestas posibles: pecho, espalda o costado. Pecho y espalda son MURO en los tres gestos, sin excepcion; si es una de esas dos, ya has terminado, estas parado. PASO 3: si ves un COSTADO, mira si el brazo derecho esta extendido hacia delante. Si NO lo esta (brazos bajados o en cruz), los dos costados abren, pero solo para seguir RECTO o GIRAR A LA DERECHA: ni izquierda ni media vuelta. PASO 4: si el brazo SI esta extendido, ya no valen los dos costados, solo el IZQUIERDO, y ese pasa en todas las direcciones. Para saber que costado ves: el brazo derecho apunta hacia donde el agente mira, asi que si la porra sale hacia TU izquierda estas viendo su hombro izquierdo y pasas; si sale hacia tu derecha, ves el derecho y esperas. TRUCO DEL EJE, util en las escenas con cuatro coches: dibuja la linea que une los hombros del agente y prolongala. Los coches que caen SOBRE ese eje son los costados; los que caen perpendiculares a el son el pecho y la espalda. CASOS RESUELTOS. Caso 1, agente de cara a ti con brazos bajados (5834, 5839): el eje une amarillo y azul, que pasan recto o derecha; rojo (pecho) y verde (espalda) parados. Caso 2, mismo gesto con el agente girado hacia el amarillo (5837, 5841): el eje une rojo y verde, que ahora son los que pasan; amarillo (pecho) y azul (espalda) parados. Caso 3, agente de cara a ti con el brazo derecho extendido (5857, 5867): su hombro izquierdo cae a TU derecha, asi que pasa solo el azul, y los otros tres estan parados incluido el amarillo al que apunta la porra. Caso 4, agente de perfil hacia el amarillo con el brazo extendido (5859, 5869): desde el primer plano ves su hombro izquierdo, asi que pasas TU (el rojo) y nadie mas. LOS TRES ENGANOS QUE MAS PUNTOS CUESTAN. Uno: que la porra te senale NO te da paso; el brazo define quien pasa, no hacia donde vas tu. Dos: con brazos bajados, el costado NO significa via libre, significa recto o derecha; girar a la izquierda esta prohibido incluso teniendo paso. Tres: el hombro DERECHO abre con los brazos bajados y se CIERRA en cuanto el brazo se extiende; mismo costado, respuesta opuesta. Y una cuarta de vocabulario: «Внимание, спри!» lleva las dos palabras; «Внимание» a secas es un distractor, porque avisar no es ordenar parar."},
{id:"ksemaforo",im:[{f:"41967",q:"5900",a:"Rojo + ambar a la vez: SIGUE PROHIBIDO. Solo anuncia que llega el verde. Prepararse si, moverse no."},{f:"1098228160",q:"11584",a:"Ambar FIJO solo: Vnimanie, spri. Prohibido entrar; solo sigue quien ya entro o no puede parar sin frenazo peligroso."},{f:"43602",q:"5914",a:"Rojo + FLECHA VERDE a la derecha: se abre solo esa direccion. Recto e izquierda siguen prohibidos. Y el giro se hace cediendo."}],t:"El semaforo: significado oficial de cada senal",art:"ЗДвП чл. 12 / ППЗДвП чл. 31 y 33",p:"5884, 5900, 5906, 5914, 5922, 5923, 5925, 5934, 5940, 5950, 6581, 6582, 6583, 11584",
txt:"LOS NOMBRES OFICIALES, que es lo que pregunta el examen. VERDE FIJO: «Преминаването е разрешено», el paso esta permitido. Autoriza el movimiento, NO decide direcciones ni da prioridad: sigues cediendo a los peatones que cruzan con su verde y a quien ya esta dentro. Y no debes entrar si vas a quedarte bloqueado dentro por una retencion. AMBAR FIJO (немигащ): «Внимание, спри!», Atencion para. Prohibe entrar; la unica excepcion es quien no puede detenerse sin crear peligro, y quien ya entro debe despejar. ROJO: «Преминаването е забранено». ROJO + AMBAR: sigue siendo забранено, y ademas anuncia que el verde llega: preparate. AMBAR INTERMITENTE (мигащ): cruce no regulado, pasa con precaucion — es OTRA senal, no confundir con el ambar fijo. ROJO INTERMITENTE o dos rojas alternas: paso prohibido; es la de pasos a nivel, puentes moviles y salidas de emergencia, y vale para TODOS, no solo para tranvias. BLANCO-LUNAR de parpadeo LENTO en un paso a nivel: no ordena nada, informa de que la instalacion funciona correctamente. FLECHA VERDE junto a un rojo: abre unicamente la direccion que dibuja, y se pasa cediendo. SEMAFOROS DE CARRIL en portico (чл. 33 ППЗДвП): rojo con forma de aspa = carril cerrado; verde con forma de flecha hacia abajo = carril abierto; si ninguno luce, manda la senal Д1, y si tampoco hay Д1, no se entra en ese carril.",
cl:"LA ESCALERA DE AUTORIDAD, de mayor a menor: agente regulador, semaforo, senales verticales, marcas viales, reglas generales de prioridad. Cuando dos escalones se contradicen manda el mas alto, y casi todas las preguntas de conflicto se resuelven senalando el escalon mas alto que aparezca en la escena (5940 y 5950). METODO PARA LEER UN SEMAFORO: 1) mira si el enunciado dice немигащ o мигащ, fija o intermitente: el ambar cambia de significado entero segun eso; 2) mira que focos estan encendidos, no cual te llama mas la atencion; 3) mira si hay flecha, porque una flecha verde abre SOLO su direccion. LOS CUATRO CEBOS DE LA FAMILIA. Uno: rojo+ambar se lee como arranca ya, y es prohibido. Dos: ambar solo prohibe, pero su nombre oficial es Внимание спри, no Преминаването е забранено, y hay preguntas que califican el nombre. Tres: verde no significa en todas las direcciones ni recto y derecha; esa formula pertenece al agente regulador, no al semaforo. Cuatro: apagado no es permiso — un semaforo de carril sin luces cierra el carril si no hay Д1 que lo supla."},
{id:"kcarriles",im:[{f:"62058",q:"6090",a:"DOS carriles en mi sentido: invadir el contrario esta PROHIBIDO siempre, ni para adelantar. Ya tengo carril propio para hacerlo."},{f:"270043211",q:"9839",a:"UN carril por sentido: invadir el contrario SI se permite, pero solo por dos motivos: adelantar o rodear un obstaculo parado."},{f:"270043012",q:"9835",a:"Linea AMARILLA y BUS pintado: carril reservado a las lineas regulares de transporte publico. Que este vacio no te autoriza."}],t:"Carriles y lineas: quien puede ir por donde",art:"ЗДвП, Раздел III y Наредба № 2 (маркировка)",p:"5375, 6090, 6312, 6446, 9835, 9838, 9839, 9840, 11585, 11685, 11687",
txt:"CUANTOS CARRILES TIENE MI SENTIDO. Es la primera pregunta, porque cambia la respuesta entera. Con UN carril por sentido, invadir el contrario esta permitido por dos motivos y solo dos: изпреварване, adelantar a alguien que se mueve, y заобикаляне, rodear algo parado en tu carril. Con DOS O MAS carriles en tu sentido, invadir el contrario esta prohibido SIEMPRE, sin excepcion, porque ya tienes carril propio para adelantar. DONDE ME COLOCO. La regla general es circular por el carril mas a la derecha que este libre; los de la izquierda son para adelantar, no para viajar. Hay UNA excepcion, y exige tres condiciones a la vez: estar en poblado, que la calzada tenga dos o mas carriles en un sentido, que esten declarados con la senal Д1, y que la velocidad maxima permitida no supere 80 km/h. Fuera de poblado y en autopista no hay excepcion. EL CARRIL IZQUIERDO en via de tres carriles se cierra a quien no PUEDE alcanzar la velocidad maxima de la via (limitacion mecanica) y a quien no TIENE PERMITIDO alcanzarla (limitacion legal). No se cierra por ser conductor novel. LAS LINEAS. Прекъсната, discontinua: se puede cruzar, con intermitente y sin obligar a frenar a nadie. Непрекъсната, continua: no se cruza ni se pisa. Linea AMARILLA: delimita un carril reservado y cruzarla para circular por el esta prohibido. CARRILES RESERVADOS. BUS: solo превозни средства от редовните линии за обществен превоз на пътници, vehiculos de linea regular; ni todos los autobuses, ni los taxis, ni tu porque este vacio. LENTOS: los que llevan el distintivo бавнодвижещи се ППС y los que no pueden superar 30 km/h; se define por velocidad y distintivo, nunca por categoria de vehiculo.",
cl:"METODO EN CUATRO PREGUNTAS, por este orden. 1) Cuantos carriles tiene MI sentido: uno permite invadir el contrario con motivo, dos o mas lo prohiben siempre. 2) La linea es continua o discontinua: discontinua se cruza, continua no, amarilla es de otro. 3) Hay senal Д1 que declare los carriles: sin ella no existe la excepcion del carril comodo. 4) El carril esta reservado: BUS o lentos tienen dueno y no eres tu. LOS CUATRO CEBOS. Uno: que el carril este LIBRE nunca es un motivo, ni el contrario ni el BUS; hace falta una razon que la ley admita. Dos: dos escenas casi identicas dan respuestas opuestas segun el numero de carriles de tu sentido — es el par 9839 contra 6090 y conviene estudiarlas juntas. Tres: el circulo AZUL con un numero es velocidad MINIMA obligatoria, no maxima; azul manda, rojo prohibe. Cuatro: los taxis pueden usar el carril BUS en otros paises, en Bulgaria no salvo senal complementaria que lo diga."},
{id:"kprioridad",im:[{f:"51266",q:"5945",a:"Agente Y semaforo en verde a la vez: manda el AGENTE. En cuanto hay agente en la escena, deja de mirar lo demas."},{f:"48346",q:"6606",a:"Hay rombo amarillo, pero la tabla muestra que la preferente TUERCE a la derecha: los dos coches estan sobre ella, asi que decide la derecha (чл. 50 ал. 2)."},{f:"64819",q:"6521",a:"Ceda el paso y tabla con el trazo grueso a la izquierda-arriba: NINGUNO de los dos esta en la preferente. Entre ellos manda la derecha."}],t:"Prioridad en cruces: la escalera y la regla de la derecha",art:"ЗДвП чл. 37 y чл. 50",p:"5367, 5369, 5924, 5926, 5927, 5929, 5931, 5935, 5942, 5944, 5945, 5949, 5952, 6231, 6233, 6234, 6318, 6506, 6516, 6518, 6521, 6522, 6525, 6540, 6557, 6558, 6561, 6575, 6595, 6597, 6606, 6608, 6668, 7962, 7963, 7964",
txt:"LA ESCALERA DE AUTORIDAD, de mayor a menor: 1 agente regulador, 2 semaforo, 3 senales verticales de prioridad, 4 marcas viales, 5 reglas generales (la derecha). Se recorre de arriba abajo y te paras en el PRIMER escalon presente en la escena; los de abajo ni se plantean. Matiz importante: el semaforo solo desplaza a las senales de PRIORIDAD. Las de obligacion, prohibicion y direccion siguen vigentes con el verde encendido, porque el semaforo decide CUANDO pasas, no HACIA DONDE. COMO LEER LAS SENALES DE PRIORIDAD. El rombo amarillo dice que mandas sobre las vias que te cruzan. La tabla que cuelga debajo dice POR DONDE VA la preferente: trazo GRUESO es la preferente, trazo FINO es secundaria. Si la tabla muestra que la preferente TUERCE y el otro coche tambien esta sobre ella, la senal deja de repartir y vuelve la regla de la derecha — es el чл. 50, ал. 2. Y un ceda el paso NO significa que el otro tenga preferencia: significa que ambos debeis cedersela a un tercero; si ese tercero no esta, entre vosotros manda la derecha. EL GIRO A LA IZQUIERDA es una regla aparte, чл. 37: quien gira a la izquierda cede a los que circulan en sentido contrario. Actua a la vez que todo lo demas y no lo anula el rombo: estar en la via con prioridad te da preferencia sobre los laterales, no sobre quien viene de cara por tu misma via.",
cl:"LO QUE NUNCA DA PRIORIDAD, y son los cuatro cebos que mas se repiten en el bloque. Uno: IR RECTO. Ni girar, ni seguir de frente, ni dar la vuelta otorgan preferencia; la maniobra que elijas no es fuente de derecho. Dos: SENALIZAR PRIMERO. El intermitente anuncia una intencion, no la autoriza; poner el intermitente antes que el otro no compra el paso. Tres: IR MAS ADELANTADO. Medio coche por delante es una posicion de hecho, no un titulo. Cuatro: AVISAR CON CLAXON O LUCES. No crean derechos; avisar de que vas a infringir sigue siendo infringir. Y un quinto error, este de metodo: aplicar la regla de la derecha ANTES de mirar si hay senales. La derecha es el ultimo escalon, no el primero. PAREJAS QUE CONVIENE ESTUDIAR JUNTAS: 6540 y 6561 son la misma escena con el rojo cambiado de sitio — a la izquierda te cede, de frente si giras a la izquierda no; 5944 y 5945 son el agente contra la senal y contra el semaforo; 6606 y 6521 se resuelven leyendo el GROSOR del trazo de la tabla; 6518 y 6522 son el MISMO ceda el paso con la tabla girada y respuestas contrarias — en 6518 el otro coche cae sobre el trazo grueso y pierdes, en 6522 cae sobre el fino y ganas, asi que lo que decide no es TU senal sino donde cae el OTRO; 6557 y 6558 son la misma escena con el coche cambiado de lado y valen un punto entero por acertar de que ventanilla te llega. TRES MATICES QUE SOLO APARECEN EN LA SEGUNDA TANDA. Uno: el semaforo apaga la regla de la derecha pero NO apaga el чл. 37; entre dos vehiculos que tienen verde a la vez, el que gira a la izquierda sigue cediendo al de frente (5935). Dos: incorporarse a una via NO es un cruce; quien entra cede a quien ya circula, y la regla de la derecha no interviene aunque el que entra venga por la derecha (5367). Tres: en las preguntas de tipo «que reglas se aplican», una regla puede ser cierta y aun asi ser respuesta FALSA si en esa imagen no hay nadie a quien aplicarsela (5929). Ser verdadera no basta, tiene que ser pertinente.EL TRIO 5927 / 5929 / 5931 tiene las MISMAS tres opciones y cambian las correctas segun un solo detalle: si la senal lleva TABLA y la preferente TUERCE, entre sus vehiculos manda la derecha; si NO lleva tabla y la preferente sigue RECTA, sus vehiculos se encuentran de frente y manda el чл. 37, no la derecha. La ausencia de tabla es informacion. Y OJO A LA PALABRA «SOLO» en las opciones: en este banco casi siempre convierte una verdad parcial en una falsedad. UNA CATEGORIA APARTE: la INCORPORACION. Salir de un estacionamiento, de un patio o entrar desde un carril de aceleracion NO es un cruce: cede siempre el que entra, y la regla de la derecha no interviene aunque el que entra venga por la derecha (5367, 5369, 6231). Antes de aplicar reglas de cruce, comprueba que lo que tienes delante sea un cruce."},
{id:"kpeatones",im:[{f:"270044419",q:"9853",a:"Peaton cruzando por un paso: hay que cederle. Ceder no es frenar un poco: es no obligarle a pararse, apurar el paso ni desviarse."},{f:"270044468",q:"9854",a:"Paso marcado con lineas DISCONTINUAS: protege igual que una cebra. La obligacion no nace del dibujo del suelo."}],t:"Peatones: cuando hay que cederles el paso",art:"ЗДвП, Раздел XI",p:"9853, 9854, 9856",
txt:"LA IDEA DE FONDO, y es la que resuelve todas las preguntas de esta familia: la proteccion del peaton NO depende de que el paso este pintado ni de que haya una senal. Depende de que el peaton este cruzando donde tiene derecho a cruzar. UN PASO DE PEATONES existe y obliga tanto si esta marcado con la cebra clasica, como si lo esta con lineas discontinuas, como si no tiene ninguna marca vial y solo lo indica la senal o la propia configuracion del lugar. EN LAS INTERSECCIONES los peatones pueden cruzar la calzada por la PROLONGACION de la acera, este marcada o no. Esa prolongacion imaginaria es zona de peatones aunque el asfalto este liso, y al girar hay que contar con ella. QUE SIGNIFICA CEDER: no obligar al peaton a detenerse, a acelerar el paso ni a cambiar su trayectoria. Si tiene que apurar por ti, no le has cedido. Y con varios carriles la obligacion es de cada conductor por separado: que el coche de al lado no pare no te autoriza a pasar, y ademas te tapa la vision.",
cl:"EL DISTRACTOR DE ESTA FAMILIA ES SIEMPRE EL MISMO: condicionar la proteccion del peaton a un requisito de forma. «Solo cuando es de tipo cebra», «solo cuando lo indica una senal», «solo cuando esta marcado». Fijate en la palabra SOLO: en las tres preguntas del bloque, las opciones falsas la llevan y las correctas no. Es el mejor atajo de todo el banco: en cuanto veas «solo» o «siempre» en una opcion sobre peatones, desconfia. REGLA PRACTICA PARA LA CALLE, que ademas es la que el examen premia: al girar en una interseccion, mira la prolongacion de la acera que vas a cruzar antes que a los coches. Girar mirando solo el trafico es el error que mas atropellos causa en ciudad."}
];
